name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy project files to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: "./"
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Run build & start commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to project
            cd ${{ secrets.TARGET_DIR }}

            # Update packages and install Node.js (Ubuntu-based)
            sudo apt update -y
            sudo apt install curl -y
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt install -y nodejs

            # Install dependencies
            npm install

            # Build Next.js project
            npm run build

            # Install PM2 to keep app running
            sudo npm install -g pm2

            # Start or restart app using PM2
            pm2 delete nextjs-app || true
            pm2 start npm --name "nextjs-app" -- start
            pm2 save
